service: tarmizi-serverless-i
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  function-one:
    handler: index.firsthandler
    events:
      - httpApi:
          path: /
          method: get
  function-two:
    handler: index.secondhandler
    events:
      - httpApi:
          path: /mizi
          method: post

plugins:
  - serverless-offline
