service: tarmizi-serverless-i
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  deploymentBucket:
    name: cohort5.deployment

functions:
  function-one:
    handler: index.firsthandler
    events:
      - httpApi:
          path: /
          method: get
      - sqs:
          arn: arn:aws:sqs:us-east-1:255945442255:tarmizi-sqs
  function-two:
    handler: index.secondhandler
    events:
      - httpApi:
          path: /mizi
          method: post

plugins:
  - serverless-offline
